// ============================================================
// FILE: app/robots.js
// PURPOSE: Tells search engine crawlers what to index and what
//          to skip — protects API routes and form pages from
//          being indexed by Google
// LAST CHANGED: May 14, 2026
// WHY IT EXISTS: Without this file Google may attempt to crawl
//               and index API routes, form pages, and edit pages
//               which have zero SEO value and waste crawl budget
// DEPENDENCIES: None — Next.js reads this file automatically
// ⚠️ DO NOT CHANGE: /api/ must always stay disallowed — API routes
//                   should never appear in Google search results
// ============================================================

// May 14, 2026 REASON: SEO architecture rule from brain dump —
// protect crawl budget, never index API or form pages
export default function robots() {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',           // API routes — never index
          '/ask',            // Ask form — no SEO value, duplicate of question pages
          '/profile/*/edit', // Profile edit pages — private settings
        ],
      },
    ],
    sitemap: 'https://community.therealmedico.store/sitemap.xml',
  };
}

// --- CHANGE LOG ---
// [May 14, 2026] CREATED: Initial build
// REASON: Phase 1 SEO requirement — robots.txt auto-generated by Next.js
// --- END CHANGE LOG ---
